spring:
  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: true
      # если задан профиль , можно указать
      profiles:
        active: dev
      #file: compose.yml
      #host:
      skip:
        in-tests: true
      lifecycle-management: start_and_stop
      start:
        log-level: info
        command: up
      stop:
        command: down #если down, то контейнер будет удален после установки
      readiness:
        timeout: 2m
        tcp:
          connect-timeout: 200ms
        wait: always